version: '3.8'

services:
  be1:
    build:
      context: .
      dockerfile: be1.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - be2

  be2:
    build:
      context: .
      dockerfile: be2.Dockerfile
    ports:
      - "50051:50051"
