name: Build and Dockerize

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name:  Install dependencies for be1
        working-directory: be1
        run: npm ci

      - name:  Build be1
        working-directory: be1
        run: npm run build

      - name:  Install dependencies for be2
        working-directory: be2
        run: npm ci

      - name:  Build be2
        working-directory: be2
        run: npm run build

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name:  Build be1 Docker image
        run: docker build -f docker/be1.Dockerfile -t be1:latest .

      - name:  Build be2 Docker image
        run: docker build -f docker/be2.Dockerfile -t be2:latest .